// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaXiHXr1irJIcKwe62LDFQiCpY6iOE0cw',
    appId: '1:469675949347:android:b29fba97822c4c8209a096',
    messagingSenderId: '469675949347',
    projectId: 'spontane-gog47y',
    storageBucket: 'spontane-gog47y.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiPqgCbT5cENmhST8xu4tZusEfOpcUleo',
    appId: '1:469675949347:ios:ec6f73a33c508dd909a096',
    messagingSenderId: '469675949347',
    projectId: 'spontane-gog47y',
    storageBucket: 'spontane-gog47y.appspot.com',
    androidClientId: '469675949347-j03ce8is6msbgc08foh4fccd1iuenqop.apps.googleusercontent.com',
    iosClientId: '469675949347-f0tp4im6lfthjme78184il1h99otpq0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.spontane',
  );
}
